---
- name: Manage documents in a Retrieval-Augmented Generation (RAG) setup
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Specific API agentx - Transfer or Submit a document in a Retrieval-Augmented Generation (RAG) setup
      ibm.ce_emea_rag.rag_document:
        rag_agent_id: "{{ rag_agent_id }}"
        rag_file_name: Red_Hat_Partner Training_Portal_User_Guide.pdf
        rag_file_url: http://localhost/pdf/Red_Hat_Partner_Training_Portal_User_Guide.pdf
        rag_chunk_overlap: 150
        rag_chunk_size: 400
        rag_keep_files: false
        method: CREATE
      register: create_result






