---
- name: Delete user by username
  hosts: localhost
  roles:
    - role: ibm.ce_emea_petstore.delete_user_by_username
      vars:
        user_endpoint: https://petstore.swagger.io/v2/user
        username: "johndoe"
