---

- name: Manage pets for Petstore using petstore API from https://petstore.swagger.io/
  hosts: localhost
  gather_facts: true
  vars:
    local_pet_id: 123
    local_pet_endpoint: "https://petstore.swagger.io/v2/pet"
    local_pet_name: "Tess"

  tasks:
    #- name: Petstore API - Add pet

    #- name: Petstore API - Find pets by status

    #- name: Petstore API - Get pet by ID

    #     prompt: "Do you want to continue(yes/no)?"
    #   register: my_pause
    #   delegate_to: localhost

    #- name: Petstore API - Delete pet by ID
