---
- name: Sample Ansible playbooks to manage Artificial Intelligence (AI) assistant agents within a Retrieval-Augmented Generation (RAG) system
  hosts: localhost
  gather_facts: false 
  tasks:
    - name: Create an AI assistant agent within a Retrieval-Augmented Generation (RAG) system
      ibm.ce_emea_rag.rag_agent:
        rag_workspace_id: "{{ rag_workspace_id }}"
        agent_name: "{{ agent_name }}"
        method: CREATE
      register: create_result
