---
- name: Create a user
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Include create user role
      ansible.builtin.include_role:
        name: ibm.ce_emea_petstore.create_user
      vars:
          user_endpoint: https://petstore.swagger.io/v2/user
          user_id: 1
          username: "johndoe"
          first_name: "John"
          last_name: "Doe"
          email: "john.doe@example.com"
          password: "password123"
          phone: "123-456-7890"
          user_status: 1
