---
- name: Sample Ansible playbooks to manage documents in a Retrieval-Augmented Generation (RAG) architecture
  hosts: localhost
  gather_facts: false
  module_defaults:
    ibm.ce_emea_rag.rag_document:
      rag_api_base_url: https://rag-turbo-app-rag-turbo.apps.wxai-ocp-ga.p126.cesc.nca.ihost.com/api
      rag_username_api: fabrice.livigni@free.fr
      rag_password_api: password
      rag_api_key: sk_wrk_2MRLdOtcHpgadUefAIuW2o1l2qXZ3Qkscynkd4eXxOs9OZun

  tasks:


    - name: Get a list of documents in a Retrieval-Augmented Generation (RAG) architecture
      ibm.ce_emea_rag.rag_document:
        rag_agent_id: clxt6tle8000777c1ssbpf9b2
        method: LIST
      register: get_result

    - name: Display the list of RAG documents
      debug:
        var: get_result.json_payload

    - name: Get or Retrieve a document by its ID  in a Retrieval-Augmented Generation (RAG) architecture
      ibm.ce_emea_rag.rag_document:
        rag_agent_id: clxt6tle8000777c1ssbpf9b2
        rag_document_id: "{{ get_result.json_payload[0].id  }}"
        method: GET_BY_ID
      register: get_by_id_result

    - name: Display the RAG document info
      debug:
        var: get_by_id_result.json_payload


    - name: Transfer or Submit a document in a Retrieval-Augmented Generation (RAG) architecture
      ibm.ce_emea_rag.rag_document:
        rag_agent_id: clxt6tle8000777c1ssbpf9b2
        rag_file_name: Red_Hat_Partner Training_Portal_User_Guide.pdf
        rag_file_url: http://localhost/pdf/Red_Hat_Partner_Training_Portal_User_Guide.pdf
        rag_chunk_overlap: 150
        rag_chunk_size: 400
        rag_keep_files: false
        method: CREATE
      register: create_result

    - name: Display the output of the document ingestion
      debug:
        var: create_result.json_payload

    - pause:
        prompt: "Do you want to continue(yes/no)?"
      register: my_pause
      delegate_to: localhost


    - name: Remove or Delete a document by its ID in a Retrieval-Augmented Generation (RAG) architecture
      ibm.ce_emea_rag.rag_document:
        rag_agent_id: "clxt6tle8000777c1ssbpf9b2"
        rag_document_id: "{{ create_result.json_payload.id }}"
        method: DELETE
      register: delete_result

    - name: Display the delete document result
      debug:
        var: delete_result.json_payload





