---
- name: Delete user by username
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Include delete user by username role
      ansible.builtin.include_role:
        name: ibm.ce_emea_petstore.delete_user_by_username
      vars:
        user_endpoint: https://petstore.swagger.io/v2/user
        username: "johndoe"
