---
- name: Manage Artificial Intelligence (AI) assistant agents into a Retrieval-Augmented Generation (RAG) structure
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Specific API agentx - Create an AI assistant agent into a Retrieval-Augmented Generation (RAG) structure
      ibm.ce_emea_rag.rag_agent:
        rag_workspace_id: "{{ rag_workspace_id }}"
        agent_name: "{{ agent_name }}"
        method: CREATE
      register: create_result
