---
- name: Manage documents within a Retrieval-Augmented Generation (RAG) system
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Specific API agentx - Get a list of documents within a Retrieval-Augmented Generation (RAG) system
      ibm.ce_emea_rag.rag_document:
        rag_agent_id: "{{ rag_agent_id }}"
        method: LIST
      register: get_result
