---
- name: Manage documents within a Retrieval-Augmented Generation (RAG) system
  hosts: localhost
  gather_facts: False
  module_defaults:
    ibm.ce_emea_rag.rag_document:
      rag_api_base_url: https://rag-turbo-app-rag-turbo.apps.wxai-ocp-ga.p126.cesc.nca.ihost.com/api
      rag_username_api: fabrice.livigni@free.fr
      rag_password_api: password
      rag_api_key: sk_wrk_2MRLdOtcHpgadUefAIuW2o1l2qXZ3Qkscynkd4eXxOs9OZun

  tasks:
    - name: Get a list of documents within a Retrieval-Augmented Generation (RAG) system
      ibm.ce_emea_rag.rag_document:
        rag_workspace_id: "{{ rag_workspace_id }}"
        method: LIST
      register: get_result

    - name: Get or Retrieve a document by its ID within a Retrieval-Augmented Generation (RAG) system
      ibm.ce_emea_rag.rag_document:
        rag_workspace_id: "{{ rag_workspace_id }}"
        rag_document_id: "{{ get_result.json_payload[0].id }}"
        method: GET_BY_ID
      register: get_by_id_result

    - name: Embed a document within a Retrieval-Augmented Generation (RAG) system    
      ibm.ce_emea_rag.rag_document:
        rag_workspace_id: "{{ rag_workspace_id }}"
        rag_document_id: "{{ get_by_id_result.json_payload.payload.payload.id }}"
        rag_chunk_overlap: 1500
        rag_chunk_keep_size: 40
        rag_keep_files: 10
        rag_keep_method: LIST
      register: embed_result

    #- name: Remove or Delete a document by its ID within a Retrieval-Augmented Generation (RAG) system





    
