---
- name: Deploy simple website using Ansible Lightspeed with watsonx Code Assistant
  hosts: all
  gather_facts: false
  remote_user: root
  become: true

  tasks:
    - name: Ensure httpd package is installed
      ansible.builtin.package:
        name: httpd
        state: present


    - name: Configure httpd on port 8080
      ansible.builtin.uri:
        url: http://localhost:8080/api/v1/inventory/add
        method: POST
        body:
          category_id: 1
          category_name: Dogs
          category_description: The best dog's in the world.
          category_status: 1
        return_content: true
        status_code: 201


    # Start and enable firewalld & Allow the traffic through firewalld & reload firewalld & Ensure /var/www/html directory exists
    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow the traffic through firewalld
      ansible.posix.firewalld:
        port: "{{ _port_ }}"
        permanent: true
        state: enabled

    - name: Reload firewalld
      ansible.builtin.command: firewall-cmd --reload

    - name: Ensure /var/www/html directory exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'

  
    #- name: Extract website-rh.tar.gz without remote_src and set permissions and ownership to root
    

    - name: Start and enable httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true






