---
- name: Delete purchase order by ID
  ansible.builtin.uri:
    url: "{{ pet_endpoint }}/order/{{ order_id }}"
    method: DELETE
    headers:
      Content-Type: "application/json"
    return_content: yes
  register: result

- name: Debug result
  debug:
    var: result
