---
- name: Manage Artificial Intelligence (AI) assistant agents in a Retrieval-Augmented Generation (RAG) architecture
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get an AI assistant agent by its ID in a Retrieval-Augmented Generation (RAG) architecture
      ibm.ce_emea_rag.rag_agent:
        rag_workspace_id: "{{ rag_workspace_id }}"
        rag_agent_id: "{{ rag_agent_id }}"
        method: GET_BY_ID
      register: get_by_id_result
      