namespace: "ibm"
name: "ce_emea_rag"
version: "1.1.0"
readme: "README.md"
authors:
    - "Jay W Carman"
    - "Anilkumar C M"
    - "Kavya Handadi"
    - "Umar Ali"
description: "Ansible modules collection for IBM cloud."
license:
    - "FAB-1.0"
issues: "https://github.com/IBM-Cloud/ansible-collection-ibm/issues"
tags:
    - ibm
    - ceemear
    - rag

repository: "https://github.com/.."