---
- name: Get store inventory
  ansible.builtin.uri:
    url: "{{ pet_endpoint }}/inventory"
    method: GET
    headers:
      Content-Type: "application/json"
    return_content: yes
  register: result

- name: Debug result
  debug:
    var: result
