---
- name: Sample RAG Ansible playbooks to manage RAG Documents
  hosts: localhost
  gather_facts: True
  tasks:


    - name: Get a list of RAG documents
      ceemea.rag.document:
        rag_agent_id: clxt6tle8000777c1ssbpf9b2
        method: LIST
      register: get_result

    - name: Display the list of RAG agents
      debug:
        var: get_result.json_payload

    - name: Get a RAG document by its ID
      ceemea.rag.document:
        rag_agent_id: clxt6tle8000777c1ssbpf9b2
        rag_document_id: "{{ get_result.json_payload[0].id  }}"
        method: GET_BY_ID
      register: get_by_id_result

    - name: Display the RAG document info
      debug:
        var: get_by_id_result.json_payload

    - name: Create a RAG document
      ceemea.rag.document:
        rag_agent_id: clxt6tle8000777c1ssbpf9b2
        rag_file_name: Red_Hat_Partner Training_Portal_User_Guide.pdf
        rag_file_url: http://localhost/pdf/Red_Hat_Partner_Training_Portal_User_Guide.pdf
        rag_chunk_overlap: 150
        rag_chunk_size: 400
        rag_keep_files: false
        method: CREATE
      register: create_result

    - name: Display the output of Create a RAG agent
      debug:
        var: create_result.json_payload

    # - name: Delete a RAG document by its ID
    #   ceemea.rag.document:
    #     rag_agent_id: "clxt6tle8000777c1ssbpf9b2"
    #     rag_document_id: "clxvyxb5c006077c1bw48gknj"
    #     method: DELETE
    #   register: delete_result

    # - name: Display the delete document result
    #   debug:
    #     var: delete_result.json_payload

    # - name: Create a RAG agent
    #   ceemea.rag.agent:
    #     rag_workspace_id: "clxt68sy6000277c1q434saj3"
    #     agent_name: "Lorenzo9 Charenton"
    #     method: CREATE
    #   register: create_result

    # - name: Display the output of Create a RAG agent
    #   debug:
    #     var: create_result.json_payload

    # - name: Update a RAG agent
    #   ceemea.rag.agent:
    #     rag_workspace_id: "clxt68sy6000277c1q434saj3"
    #     rag_agent_id: "{{create_result.json_payload.id}}"
    #     agent_name: "Lorenzo Livigni4"
    #     method: UPDATE
    #   register: update_result

    # - name: Display the output of Create a RAG agent
    #   debug:
    #     var: update_result.json_payload

    # - name: Get a RAG agent by its ID
    #   ceemea.rag.agent:
    #     rag_workspace_id: "clxt68sy6000277c1q434saj3"
    #     rag_agent_id: "{{create_result.json_payload.id}}"
    #     method: GET_BY_ID
    #   register: get_by_id_result

    # - name: Display the agent info
    #   debug:
    #     var: get_by_id_result.json_payload

    # - name: Delete a RAG agent by its ID
    #   ceemea.rag.agent:
    #     rag_workspace_id: "clxt68sy6000277c1q434saj3"
    #     rag_agent_id: "{{create_result.json_payload.id}}"
    #     method: DELETE
    #   register: delete_result

    # - name: Display the delete agent result
    #   debug:
    #     var: delete_result.json_payload

