---
- name: Custom Sample RAG Ansible playbooks to manage RAG Agents
  hosts: localhost
  gather_facts: True
  tasks:


    - name: Get a list of RAG agents
      ceemea.rag.agent:
        rag_workspace_id: "clxt68sy6000277c1q434saj3"
        method: LIST
      register: get_result

    - name: Display the list of RAG agents
      debug:
        var: get_result.json_payload

    - name: Create a RAG agent
      ceemea.rag.agent:
        rag_workspace_id: clxt68sy6000277c1q434saj3
        agent_name: Lorenzo10 Charenton10
        method: CREATE
      register: create_result

    - name: Display the output of Create a RAG agent
      debug:
        var: create_result.json_payload

    - name: Update a RAG agent
      ceemea.rag.agent:
        rag_workspace_id: clxt68sy6000277c1q434saj3
        rag_agent_id: "{{create_result.json_payload.id}}"
        agent_name: "Lorenzo5 Livigni5"
        method: UPDATE
      register: update_result

    - name: Display the output of Create a RAG agent
      debug:
        var: update_result.json_payload

    - name: Get a RAG agent by its ID
      ceemea.rag.agent:
        rag_workspace_id: clxt68sy6000277c1q434saj3
        rag_agent_id: "{{create_result.json_payload.id}}"
        method: GET_BY_ID
      register: get_by_id_result

    - name: Display the agent info
      debug:
        var: get_by_id_result.json_payload

    - name: Delete a RAG agent by its ID
      ceemea.rag.agent:
        rag_workspace_id: clxt68sy6000277c1q434saj3
        rag_agent_id: "{{create_result.json_payload.id}}"
        method: DELETE
      register: delete_result

    - name: Display the delete agent result
      debug:
        var: delete_result.json_payload

