---
- name: OCP Cluster Operation
  hosts: localhost
  connection: local
  gather_facts: false
  #module_defaults:
  #  group/community.okd.okd:
  #     host: https://api.tnc-env23.p157.cesc.nca.ihost.com:6443
  #     verify_ssl: false

  vars:
    openshift_admin: kubeadmin
    openshift_namespace: cp4aiops
    openshift_api_url: api.tnc-env23.p157.cesc.nca.ihost.com:6443

  tasks:
  - block:
    # It's good practice to store login credentials in a secure vault and not
    # directly in playbooks.
    - name: Include variables from 'openshift_passwords.yml'
      include_vars: openshift_passwords.yml

    - name: Log in Openshift
      ansible.builtin.command: oc login --username {{ openshift_admin }} --password {{ openshift_password
        }}
      register: openshift_login_result


    - name: Generate a list of all pods from an openshift namespace using API Key authentication
      ibm.ce_emea_rag.rag_pod:
        rag_workspace_id: "{{ openshift_workspace_id }}"
        method: LIST
      register: get_result


    - name: extract each pod name and generate an array of json object whose key is name and value is the pod name
      ansible.builtin.set_fact:
        rag_pods: "{{ get_result.json_payload[0].name }}"


    #- name: print the array

    #- name: create a json file from the array and the json file name is the openshift namespace 





    

