---
- name: Manage orders for Petstore using petstore API from https://petstore.swagger.io/
  hosts: localhost
  gather_facts: true
  vars:
    local_order_id: 1
    local_pet_endpoint: https://petstore.swagger.io/v2/store
    
  tasks:
    - name: Include get store inventory role
      ansible.builtin.include_role:
        name: ibm.ce_emea_petstore.get_inventory
      vars:
        pet_endpoint: "{{ local_pet_endpoint }}"


    - name: Include place order for a pet role
      ansible.builtin.include_role:
        name: ibm.ce_emea_petstore.place_order
      vars:
        pet_endpoint: "{{ local_pet_endpoint }}"
        order_id: "{{ local_order_id }}"
        pet_id: 1
        quantity: 1
        ship_date: '2024-07-19T12:34:56.789Z'
        status: placed
        complete: true


    - name: Include get order by ID role
      ansible.builtin.include_role:
        name: ibm.ce_emea_petstore.get_order_by_id
      vars:
        pet_endpoint: "{{ local_pet_endpoint }}"
        order_id: "{{ local_order_id }}"


    - name: Include delete order by ID role
      ansible.builtin.include_role:
        name: ibm.ce_emea_petstore.delete_order_by_id
      vars:
        pet_endpoint: "{{ local_pet_endpoint }}"
        order_id: "{{ local_order_id }}"

