---
- name: Manage documents in a Retrieval-Augmented Generation (RAG) architecture
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Specific API agentx - Get a list of documents in a Retrieval-Augmented Generation (RAG) architecture
      ibm.ce_emea_rag.rag_document:
        rag_agent_id: "{{ rag_agent_id }}"
        method: LIST
      register: get_result
